### PR TITLE
add and fix couple of stuff

### PR DESCRIPTION
**Pull request by cyagon**
feat(config): add simplenote
feat(config): add visual-studio-code x86_64
fix(config): fix go x86_64
feat(config): add anydesk

### CODE REVIEW

**Comment by geek1011** [comment]
Looks good

**Comment by geek1011** [comment]
@lvillani

**Comment by cyagon** [comment]
here a bit more:

feat(config): add putty x86_64
feat(config): add ImageGlass

**Comment by cyagon** [comment]
i forgot something:

feat(config): add smplayer

**Pull request merged**
