### PR TITLE
feat(config): add visual-studio-community

### PR DESCRIPTION
**Pull request by cyagon**
#71 
like this or with "latest" as version?

### CODE REVIEW

**Comment by guiweber** [comment]
We'd need to know if the URL changes from version to version. We can put 2017 for now and if we see the URL doesn't change when they update it to 2018, then we can put "latest". Thanks!

**Comment by cyagon** [comment]
this url is a permalink to the latest version of visual-studio-community 2017. i found these links [here](https://www.visualstudio.com/de/downloads/) and [here](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio)

**Comment by geek1011** [comment]
What if someone wants an additional workload for vs?

**Comment by cyagon** [comment]
in vs2017, after the installation there is a second program called "Visual Studio Installer", which lets you modify the installation/workloads afterwards

unbenannt
unbenann2t

**Pull request merged**
