### PR TITLE
PopcornTime CE

### PR DESCRIPTION
**Pull request by KHNRV**
App submission

### CODE REVIEW

**Comment by geek1011** [comment]
@lvillani What do you think about this. Should it be included?

**Comment by Schokobecher** [comment]
I would be against this. Normally I don't 'discriminate' against softe and everyone can use w/e they want, but including PopcornTime could have a heavy backslash.

**Comment by guiweber** [comment]
@Schokobecher why do you feel could it have a heavy backslash and from who? I personally don't see the issue.

**Comment by geek1011** [comment]
@Schokobecher @guiweber I don't think there would be any major backlash, but I don't think we want to endorse this kind of software in just-install.

**Comment by Schokobecher** [comment]
@geek1011 @guiweber 
Yeah maybe backlash was the wrong word, but I fear for the reputation - or even worse getting flagged by Anti-Malware / Anti-Virus companies. PopcornTime has only one use, which is not really on the legal side of things, unlike normal BT clients.

In a sense just-install would act as a distribution platform for that software.

**Comment by geek1011** [comment]
I am going to close this for now.

**Pull request closed without merging**
