### PR TITLE
feat(config): update crystaldisk-mark

### PR DESCRIPTION
**Pull request by cyagon**

### CODE REVIEW

**Comment by guiweber** [comment]
crystaldisk mark/info should be updated by the updater. If you have time it would be nice to check what's wrong with it.

**Comment by cyagon** [comment]
the creators of crystaldisk mark/info changed the naming of their setup-files (now without "-en"): https://osdn.net/projects/crystaldiskinfo/releases/\

i tried to fix it by changing the advanced rules accordingly (and creating a messed up pull request, stupid me), but for me it didnt work.

**Comment by guiweber** [comment]
It's going to work. See my comments in https://github.com/just-install/just-install-updater/pull/39

**Comment by cyagon** [comment]
since i pushed changes to the updater, im closing the 2 pull-requests.

**Pull request closed without merging**
