### PR TITLE
Add Timecamp

### PR DESCRIPTION
**Pull request by karololszacki**
latest should be: 1.6.1.0

### CODE REVIEW

**Comment by mimi89999** [comment]
@lvillani Do we really want interactive installers in j-i?

**Comment by lvillani** [comment]
We already have them.

**Comment by mimi89999** [comment]
I know. There are 3, but do we want more?

**Comment by lvillani** [comment]
I'm not strictly opposed to adding more, if the software is reasonably popular and people find it more convenient to get it through j-i :-)

**Pull request merged**
