### PR TITLE
Remove ffmpeg

### PR DESCRIPTION
**Pull request by mimi89999**
I might fix it one day, but for now let's remove it.

### CODE REVIEW

**Review by pgaskin — COMMENTED** [review]
Maybe change it to these ones: https://github.com/BtbN/FFmpeg-Builds/releases?

**Comment by mimi89999** [comment]
@pgaskin I saw those builds, but they have a folder with the name of the zip in the zip. Will require either changes from them or in j-i. I will open an issue there later today and ask if they could put the folders directly in the zip.

**Comment by mimi89999** [comment]
I opened https://github.com/BtbN/FFmpeg-Builds/issues/26

**Comment by mimi89999** [comment]
@pgaskin Can this be merged? ffmpeg won't be an easy fix. If there are users complaining, I can try to re add it, but keeping this broken entry gives nothing besides CI failures.

**Pull request merged**
