### PR TITLE
Add Mp3tag, Postman & Mountain Duck

### PR DESCRIPTION
**Pull request by BeatriceFendt**
Hi, this is my first PR to this awesome project and I am not sure if my changes are 100% correct.
So it would be great if you could have a look. Thank you so much! 😘

### CODE REVIEW

**Comment by geek1011** [comment]
Thanks for contributing! This mostly looks good, but you have a few syntax errors in your JSON due to missing commas and brackets. I'll fix those, then merge it once I test it.

**Comment by cyagon** [comment]
I currently cant due lacking of a current windows installation. But im looking into it in the next days when i have time.

Also, can you add me in the just-install organization? It would be really nice :)

**Comment by geek1011** [comment]
@cyagon I don't have windows right now either 😄 . As for being added, if I was able to add you, I would. @lvillani needs to add you.

**Comment by Schokobecher** [comment]
Everyone keep calm I'll check this in a few hours 😀

**Comment by cyagon** [comment]
About my windows, i crashed my partitions somehow and i was just way too lazy to reinstall it :grin: . im going to do it tomorrow and will see about the recent pull requests.

**Comment by geek1011** [comment]
@cyagon I have a hexa-boot, but windows broke it, so I just got rid of it temporarily (and haven't got a chance to put it back yet).

**Comment by Schokobecher** [comment]
Ok, sadly none of the additions work.

- Mp3tag is linking to `https://www.mp3tag.de/dodownload.html` which redirects ( I suspect Javascript) to newest version. This does not work with just-install, it download the .html and tries to execute it.
- Postman has a similar problem, it creates the following problem:
`panic: interface conversion: interface {} is nil, not []interface {} [recovered] panic: interface conversion: interface {} is nil, not []interface {}`
- Mountain Duck link works, but results in **exit status 1620**, installing it via the same link manually works fine, the msi installer does not require additional arguments to be silent
- Mullvad has the same problem as the first two.  `exec: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\just-install\\358DB609": file does not exist`

I'm not home so I can't produce any fixes till I'm back from work.

**Comment by BeatriceFendt** [comment]
Thank you so much for your support! 😘

**Comment by guiweber** [comment]
Thanks everyone!

**Pull request merged**
