### PR TITLE
Remove vpnunlimited because it can't be downloaded

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by geek1011** [comment]
Are you sure this doesn't work?

```
patrick@dpc01:~$ curl -sv https://www.vpnunlimitedapp.com/download/windows | file -
*   Trying 104.20.41.190:443...
* TCP_NODELAY set
* Connected to www.vpnunlimitedapp.com (104.20.41.190) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4664 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=EssentialSSL Wildcard; CN=*.vpnunlimitedapp.com
*  start date: Jul  2 00:00:00 2019 GMT
*  expire date: Jul 17 23:59:59 2021 GMT
*  subjectAltName: host "www.vpnunlimitedapp.com" matched cert's "*.vpnunlimitedapp.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x56127eef6dd0)
} [5 bytes data]
> GET /download/windows HTTP/2
> Host: www.vpnunlimitedapp.com
> User-Agent: curl/7.66.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
} [5 bytes data]
< HTTP/2 200 
< date: Sat, 04 Jan 2020 20:23:28 GMT
< content-type: application/octet-stream
< content-length: 37212192
* Added cookie __cfduid="dbf884973609dec98f271a970bfb64fc41578169387" for domain vpnunlimitedapp.com, path /, expire 1580761387
< set-cookie: __cfduid=dbf884973609dec98f271a970bfb64fc41578169387; expires=Mon, 03-Feb-20 20:23:07 GMT; path=/; domain=.vpnunlimitedapp.com; HttpOnly; SameSite=Lax
* Added cookie PHPSESSID="e94rksbuof7fmm0rhmihh1nfi4" for domain www.vpnunlimitedapp.com, path /, expire 0
< set-cookie: PHPSESSID=e94rksbuof7fmm0rhmihh1nfi4; path=/
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
* Added cookie csrf_token="30b312c7084176dbc2517a919436e3ea6f3da40fb550e686" for domain www.vpnunlimitedapp.com, path /, expire 1578212608
< set-cookie: csrf_token=30b312c7084176dbc2517a919436e3ea6f3da40fb550e686; expires=Sun, 05-Jan-2020 08:23:07 GMT; Max-Age=43200; path=/; domain=www.vpnunlimitedapp.com
< content-description: File Transfer
< content-disposition: attachment; filename="VPN_Unlimited_v6.4.exe"
< content-transfer-encoding: Binary
< expires: 0
< x-frame-options: SAMEORIGIN
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 54ffedacbb21f971-YYZ
< 
{ [758 bytes data]
/dev/stdin: PE32 executable (GUI) Intel 80386, for MS Windows
```

**Comment by geek1011** [comment]
OK, it does work, but the server's really slow most of the time (~20s delay). @lvillani, what do you think?

**Comment by mimi89999** [comment]
All recent CI passed, so I'm closing this.

**Comment by mimi89999** [comment]
CI is failing again. I am reopening this.

**Comment by geek1011** [comment]
I think it might be a better idea to add the new (?) SkipAudit flag I noticed in https://github.com/just-install/just-install/commit/d4d6a86b7d5278d0c2bda8365ab2b871e917462e. @lvillani?

**Comment by lvillani** [comment]
`skipAudit` is understood only by just-install `master` at the moment.

**Comment by mimi89999** [comment]
Even if it can be skipped in CI, I don't think that having an app that is failing is a good idea.

**Comment by lvillani** [comment]
It downloads and installs just fine on my test machine, but we need to make a couple of changes to its entry. I don't know exactly why we get connection errors for some packages inside the CI environment (the audit check is inherently flakey so it's not surprising, either).

**Comment by geek1011** [comment]
Let's remove it unless someone complains about it. I don't think it's worth the constant failures (and speaking of that, would someone use a VPN whose servers keep timing out...). @lvillani, what do you think?

**Comment by lvillani** [comment]
@geek1011 agreed.

**Comment by geek1011** [comment]
I couldn't edit this PR directly, so I did it locally.

**Pull request closed without merging**
