### PR TITLE
Registry with updated Notepad++

### PR DESCRIPTION
**Pull request by kokkez**
Updated Notepad++ version and added the 64 bit link.

### CODE REVIEW

**Comment by guiweber** [comment]
Thanks for pointing this out. I found that there is a bug in the updater which prevents this entry from being updated.

Could you please rebase this pull request?

**Comment by guiweber** [comment]
P.S. if you could also squash all commits into one I would appreciate since squashing is currently disabled for pull requests on this repo.

**Comment by kokkez** [comment]
I'm not at all an expert about these git things. I tried some maneuvers but I definitely failed. Was my first pull-request, done from the web interface. If you have some hints... In the meantime, sorry...

**Comment by guiweber** [comment]
Here is a good tutorial about rebasing: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

The main issue with your pull request is that you seem to have removed the registry file in a first commit, and then re-added the modified registry file in a second commit. Since it looks to git like the whole file has changed, it is very hard to see what you changed and there will be conflicts when merging if any part of the registry changed. Usually, you should have a single commit per entry you change. You don't need to delete the file and if you replace it with a new file you certainly don't have to commit the changes in between.

You also have commits that add and delete just-install-v4.json which are not problematic per se, but they are not useful and would just pollute the project's history.

So what you want to do is squash these commits into a single commit, so that only the changes that ultimately remain are seen in the history. This can be done while rebasing, but it is a rather complex operation: https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit

It might be simpler for you to just start anew, make the changes in a single commit and submit a new pull request.

I hope this helps!

**Comment by kokkez** [comment]
I agree on the whole line, I'm a beginner on github but I wanted to try. Thanks for the suggestions, I see what I can do.

**Comment by geek1011** [comment]
If you cannot do it, I can try and do it for you.

**Comment by kokkez** [comment]
For this commit it is probably the quickest path. Thank you geek1011, very appreciated. The only modification, after all, is only in the notepad++ section. Do you need that i provide something?

**Comment by guiweber** [comment]
I enabled squash and merge functionality for this repo so I was able to merge your PR cleanly.

**Comment by kokkez** [comment]
Thank you guiweber, and sorry for all this trouble...

**Comment by guiweber** [comment]
No worries, git takes some time to get used to. Thanks for your contribution!

**Pull request merged**
