### PR TITLE
feat(config): remove windows-usb-dvd-tool

### PR DESCRIPTION
**Pull request by cyagon**
abandoned: you should use [Rufus](https://rufus.akeo.ie/) instead.

### CODE REVIEW

**Comment by guiweber** [comment]
Seems it migrated there:
https://www.microsoft.com/en-us/download/details.aspx?id=56485

**Comment by cyagon** [comment]
officially it only supports windows7/8, while rufus supports win10 + various linux-isos.

**Comment by guiweber** [comment]
Still, maybe some people still use it, many are still on windows 8. I'd leave it there, it's not that old and it causes no harm.

**Comment by cyagon** [comment]
ok

**Pull request closed without merging**
