### PR TITLE
Package additions + Build fix

### PR DESCRIPTION
**Pull request by Schokobecher**
Added

- [GOG Galaxy](https://www.gog.com/galaxy)
- [Telegram Desktop](https://desktop.telegram.org/)
- [Audacity](http://www.audacityteam.org/)

also updated Calibre, so the tests aren't failing anymore.

### CODE REVIEW

**Comment by Martan404** [comment]
@lvillani @guiweber

**Comment by Schokobecher** [comment]
I resolved the `calibre `version conflict caused by e5227d3

**Comment by guiweber** [comment]
@Schokobecher Could you please just fix your indents before I merge? You are sometimes using hard tabs (in the first line of each entry) while we use two space soft tabs as a convention. Thanks!

**Comment by Schokobecher** [comment]
Fixed in 013a00c, also I switched the tab style in N++ so won't be happening again :)

**Comment by guiweber** [comment]
Thanks!

**Pull request merged**
