### PR TITLE
Added Webtorrent

### PR DESCRIPTION
**Pull request by Martan404**
Added Webtorrent

### CODE REVIEW

**Comment by Martan404** [comment]
I'm trying to update the just-install-updater too but I'm not sure I'm doing it correctly.
Would this work?
` "webtorrent": {
    "url": "https://api.github.com/repos/feross/webtorrent-desktop/releases/latest",
    "updater": {
      "x86": {
        "rule_type": "json-link",
        "selector": "browser_download_url",
        "filter": "-ia32"
      },
      "x86_64": {
        "rule_type": "json-link",
        "selector": "browser_download_url",
        "filter": "^((?!-ia32).)*$"
      }
    },
    "version_extractor": "WebTorrentSetup-v([0-9]*(?:\\.[0-9]+)*[a-z]?)\\.exe"
},`

**Comment by Martan404** [comment]
@lvillani @guiweber

**Comment by Schokobecher** [comment]
Your rule would result in:
> webtorrent : Versions found are not the same for all architectures, results rejected

caused by your `version_extractor`, which causes the `-ia32 `build to return `0` as version.

Better would be:

> "version_extractor": "WebTorrentSetup-v([.\\d]+[.]\\d{1,5})"

or even

> `"version_extractor": "([.\\d]+[.]\\d{1,5})"`

**Comment by guiweber** [comment]
@Martan404  To make sure we're still getting the windows link, I would keep the ".exe" somewhere in there. One possibility is to change the filters as follow:

For x86:
`"filter": "-ia32.exe$"`

And for x64:
`"filter": "^((?!-ia32).)*.exe$"`

And then remove the ".exe" from the version extractor since it's what prevent the link from being collected for x86 at the moment:
`"version_extractor": "WebTorrentSetup-v([0-9]*(?:\\.[0-9]+)*[a-z]?)"`

**Comment by Martan404** [comment]
@Schokobecher @guiweber Thanks guys! Gonna have a look at it. The updater part I posted before came from the Calibre code so I wasn't totally sure of how it worked exactly.

**Pull request merged**
