### PR TITLE
fix(config): make virtualbox installation silent

### PR DESCRIPTION
**Pull request by cyagon**
i played with virtualbox a bit, because it didnt install quietly. and i found this:

unbenannt

so i edited the registry accordingly.

### CODE REVIEW

**Comment by cyagon** [comment]
@geek1011

**Comment by geek1011** [comment]
Does this work, even with the vbox networking and usb drivers?

**Comment by cyagon** [comment]
i just retested it in a new windows 10 vm, and it works. even the driver messages are silent :)

**Comment by geek1011** [comment]
Thanks for testing! I also just tested and it works way better than before.

**Pull request merged**
