### PR TITLE
Update paint.net binary name to latest version

### PR DESCRIPTION
**Pull request by breadcat**

### CODE REVIEW

**Review by mimi89999 — CHANGES_REQUESTED** [review]
Your commit message describes the issue, not the change. Please change it.

**Comment by breadcat** [comment]
Changed now, is this better?

**Comment by mimi89999** [comment]
You changed the PR title. I asked you to change the commit message.

**Comment by breadcat** [comment]
I'm sorry, I'm not sure how to do this. I don't have a huge amount of experience with git.

**Comment by mimi89999** [comment]
Anyway, this is not a good solution. paint.net should either offer uncompressed installers or don't put the version in the filename in the zip. I opened https://forums.getpaint.net/topic/116984-download-extracted-installer/, but still haven't got any reply.

**Comment by mimi89999** [comment]
Sorry for the delay. Upstream still hasn't responded to my post on the forum.
I submitted https://github.com/just-install/just-install/pull/343 that should also solve the issue.

**Pull request closed without merging**
